#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=48
#PBS -N 2018_merge_ebi_biom_table
#PBS -A d411-training

cd $PBS_O_WORKDIR

#load modules and qiime
module load miniconda/python2

#loading virtualenv
echo "loading virtualenv"

source activate qiime1

# setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

#merge biom tables
#merge_otu_tables.py -i ./otu_table.biom,EBI_merged_otu_table.biom -o ./combined_otu_table.biom

# analyse core diversity
core_diversity_analyses.py -i ./combined_otu_table.biom -o ./core_output -m ./map_combined.txt -t ./97_otus.tree -e 152

#compare categories
#compare_categories.py --method permanova -i ./core_output/bdiv_even152/unweighted_unifrac_dm.txt  -m ./map_combineda.txt -c SampleType -o permanova_out_SampleType
#compare_categories.py --method permanova -i ./core_output/bdiv_even152/unweighted_unifrac_dm.txt  -m ./map_combined1.txt -c SamplePh,Year -o permanova_out_phvsyear

#summarize taxa Level 2
#summarize_taxa.py -i ./combined_otu_table.biom -L 2 -o summarized_otu_L2

#summarize taxa Level 3
#summarize_taxa.py -i ./combined_otu_table.biom -L 1 -o summarized_otu_L1

#summarize taxa Level 3
#summarize_taxa.py -i ./combined_otu_table.biom -L 3 -o summarized_otu_L3

#summarize taxa Level 
#summarize_taxa.py -i ./combined_otu_table.biom -L 2 -o summarized_otu_L2

#Anova 
#group_significance.py -i ./combined_otu_table.biom -m ./map_combineda.txt  -c SampleType -s ANOVA -o anova.txt


#kruskal_wallis L1
#group_significance.py -i ./summarized_otu_L1/combined_otu_table_L1.biom -m ./map_combineda.txt  -c SampleType -s kruskal_wallis -o kruskal_wallis_L1.txt

#kruskal_wallis L3
#group_significance.py -i ./summarized_otu_L3/combined_otu_table_L3.biom -m ./map_combineda.txt  -c SampleType -s kruskal_wallis -o kruskal_wallis_L3.txt

#kruskal_wallis L2 - vegetation
#group_significance.py -i ./summarized_otu_L2/combined_otu_table_L2.biom -m ./map_combineda.txt  -c SampleVegetation -s kruskal_wallis -o kruskal_wallis_L3_vegetatiom.txt

#kruskal_wallis L2 - pH_Type
#group_significance.py -i ./summarized_otu_L2/combined_otu_table_L2.biom -m ./map_combineda.txt  -c SamplePh -s kruskal_wallis -o kruskal_wallis_L2_pH_type.txt

#kruskal_wallis L2 - Sample_Type
#group_significance.py -i ./summarized_otu_L2/combined_otu_table_L2.biom -m ./map_combineda.txt  -c SampleType -s kruskal_wallis -o kruskal_wallis_L2_Sample_type.txt 

#kruskal_wallis L2 - SampleVegetation
#group_significance.py -i ./summarized_otu_L2/combined_otu_table_L2.biom -m ./map_combineda.txt  -c SampleVegetation -s kruskal_wallis -o kruskal_wallis_L2_Sample_Veg.txt 

#principal coordinates
#principal_coordinates.py -i ./core_output/bdiv_even152/unweighted_unifrac_dm.txt -o beta_div_unweighted_pcoa.txt

#This script automates the construction of 3D plots (kinemage format) from the PCoA output file generated by principal_coordinates.py (e.g. P1 vs. P2 vs. P3, P2 vs. P3 vs. P4, etc., where P1 is the first component).

#make_emperor.py -i ./beta_div_unweighted_pcoa.txt -m ./map_combineda.txt -b 'SampleType' -o emperor_colored_by_sample

#filter_taxa_from_otu_table.py -i ./combined_otu_table.biom -o Otu_table_bac_onlyPh.biom -p p__Gemmatimonadetes,p__Crenarchaeota


#kruskal_wallis Filtered table 
#group_significance.py -i ./Otu_table_bac_onlyPh.biom -m ./map_combineda.txt  -c SamplePh -s kruskal_wallis -o kruskal_wallis_Filt_TpH.txt

#group_significance.py -i ./Otu_table_bac_onlyPh.biom -m ./map_combineda.txt  -c SampleDepth -s kruskal_wallis -o kruskal_wallis_Filt_Tb_depth.txt

#Otu network
#make_otu_network.py -i ./combined_otu_table.biom -m ./map_combineda.txt -o otu_network

#make heatmap by SampleTYpe
#make_otu_heatmap.py -i ./summarized_otu_L2/combined_otu_table_L2.biom -m ./map_combineda.txt  -c SampleType -o heatmap_groupedby_SampleType.pdf

source deactivate 
